[package]
name = "proc-mozjs"
version = "0.1.0"
authors = ["sagudev <samo.golez@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
mozjs = { git = "https://github.com/servo/rust-mozjs", rev="ef63e568c6aaa1c0f0d1c11f49a99acff1306709"}