[package]
name = "macro"
version = "0.1.0"
authors = ["sagudev <samo.golez@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[features]
__dbg = []
default = ["__dbg"]

[dependencies]
quote = "1.0"
macro-support = { path = "../macro-support" }